In [1]:
import pandas as pd
import csv
import os

In [2]:
country = 'Pakistan'

In [3]:
df1 = pd.read_csv(
    f"/home/kg766/shreyasi_analysis/chatgpt_data/final_analyses/conversations_classfied_all_{country}.csv",
    sep="\t",
    quoting=csv.QUOTE_ALL,
    escapechar='\\',
    encoding="utf-8"
)
df1 = df1.drop_duplicates(subset=['convo_id'])
df1

,user_id,convo_id,conversation_snippet,user_timestamp,Age,Gender,Country,topic_label_fine,topic_label_coarse,Final_Topic,label_work,multitasking,human_alone,user_education,AI_education,label_asking
0,24899493,694d557c-76bc-8320-a39d-301dd2e4121d,"[user]: ""based on your interactions with me, c...",1.766676e+09,21,Male,Pakistan,other,Other/Unknown,NaN,Personal,Yes,Yes,12.0,12.0,Doing
1,24899493,693a8e26-9264-8321-9935-355fa46f839b,"[user]: ""#include<iostream>\nusing namespace s...",1.765445e+09,21,Male,Pakistan,computer_programming,Technical Help,Programming,Coursework,Yes,Yes,13.0,0.0,Expressing
2,24899493,693a5c16-1a14-8320-8190-e3af7143f949,"[user]: ""Create a program to show how member f...",1.765393e+09,21,Male,Pakistan,computer_programming,Technical Help,Programming,Coursework,NaN,NaN,12.0,0.0,Doing
3,24899493,6927e5a9-610c-8322-b12c-97d7ccbdb169,"[user]: """"",1.764222e+09,21,Male,Pakistan,unclear,Other/Unknown,NaN,Personal,No,Yes,0.0,0.0,Expressing
4,24899493,691d5ec1-230c-8322-a315-a5e027beaade,"[user]: ""In the last part of this file there a...",1.763532e+09,21,Male,Pakistan,other,Other/Unknown,NaN,Coursework,Yes,Yes,8.0,8.0,Doing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34086,24764667,672f505e-0a94-8006-b9f0-891cae3e305f,"[user]: ""can i use as fiber optics splitter as...",1.731154e+09,40,Female,Pakistan,specific_info,Seeking Information,Math & Quantitative Calculations,Work,No,Yes,12.0,16.0,Asking\n\nReason: The user’s single-word reply...
34087,24764667,672e1fcd-e398-8006-8966-2accee03c770,"[user]: ""i want to simulate laser matter inter...",1.731077e+09,40,Female,Pakistan,specific_info,Seeking Information,Math & Quantitative Calculations,Coursework,No,No,16.0,16.0,Asking
34088,24764667,672cbde1-26a8-8006-bcbe-fce9c9fe11a2,"[user]: ""i am using labview for some file read...",1.730986e+09,40,Female,Pakistan,creative_ideation,Practical Guidance,Math & Quantitative Calculations,Work,Yes,No,12.0,14.0,Asking
34089,24764667,67250052-1618-8006-8193-d87b76bdfa84,"[user]: ""i want to develop my own website for ...",1.730478e+09,40,Female,Pakistan,how_to_advice,Practical Guidance,NaN,Work,No,Yes,8.0,8.0,Expressing
34090,24764667,6720e2d3-0d50-8006-a251-6b20023c93d3,"[user]: ""how to transfer files from one comput...",1.730209e+09,40,Female,Pakistan,specific_info,Seeking Information,Math & Quantitative Calculations,Work,Yes,Yes,12.0,16.0,Asking

In [4]:
df1.columns

Index(['user_id', 'convo_id', 'conversation_snippet', 'user_timestamp', 'Age',
       'Gender', 'Country', 'topic_label_fine', 'topic_label_coarse',
       'Final_Topic', 'label_work', 'multitasking', 'human_alone',
       'user_education', 'AI_education', 'label_asking'],
      dtype='object')

In [5]:
df1 = df1[['user_id', 'convo_id', 'user_timestamp', 
                'topic_label_fine', 'topic_label_coarse','Final_Topic', 'label_asking',
                'label_work', 'multitasking', 'human_alone',
                'user_education', 'AI_education']]

In [6]:
# rename coluumn values
topic_rename_mapping = {
    'India':{
        'Immune Health Remedies': 'Health & Wellness',
        'Python Input Handling': 'Programming',
        'Word Meaning': 'Word Meaning',
        'Mobile Earning Apps': 'Online Earning',
        'Resume, Job Aoplication': 'Resume & Jobs',
        'Banking And Loans': 'Finance & Banking',
        'Chem/Bio Related': 'Science Queries',
        'Tech Help': 'Tech Help',
        'Frontend Dev': 'Frontend Development',
        'Content Writing Help': 'Content Writing Help',
        'Mathematics': 'Mathematics',
        'Current Affairs India': 'Current Affairs',
        'Ai Image Generation': 'AI Image Generation',
        'Youtube Shorts Strategy': 'YouTube Strategy',
        'Emotional Control In Trading': 'Trading Queries'},
    'Brasil': {
        'General Health & Parenting Advice': 'Health & Wellness',
        'Social Media Captions & Marketing Copy': 'Social Media & Marketing',
        'English Learning & Portuguese-English Translation': 'Portuguese-English Translation',
        'Academic & Professional Writing Assistance': 'Writing Assistance',
        'Self-Reflection, Personality & Emotional Conversations': 'Self-Reflection & Emotions',
        'Personal Finance & Digital Banking': 'Finance & Banking',
        'Education, Sustainability & General Knowledge': 'Education & General Knowledge',
        'Ai Image Generation & Prompt Engineering': 'AI Image Generation',
        'General Tech & Device Help': 'Tech Help',
        'Cooking, Recipes & Diet Advice': 'Cooking & Diet',
        'Earning Platforms': 'Online Earning',
        'Enem & Academic Study Content.': 'Academic Study Content',
        'Customer Reviews, Translations & Business Tasks': 'Business Tasks',
        'Basic Arithmetic': 'Mathematics',
        'Freelance Pricing & Home Renovation Costs.': 'Freelance Costs'},
    'Nigeria': {
        'Personal Creative Writing & Social Messages': 'Creative Writing',
        'Nigerian & World Current Affairs / General Knowledge': 'Current Affairs',
        'Medical & Biological Science Questions': 'Medical & Science Queries',
        'Content Creation, Podcasting & Digital Business': 'Content Creation Help',
        'Career Development & Job Search': 'Career Development & Job Search',
        'Bible, Religion & Literary Questions': 'Religion, Literature & Philosophy',
        'Device Setup & General Tech Help': 'Tech Help',
        'Web Development & Programming Basics': 'Web Dev & Programming',
        'Academic Writing': 'Academic Writing',
        'Energy, Electronics & Engineering Questions': 'Engineering & Electronics Queries',
        'Ai Image Generation & Visual Content Creation': 'AI Image Generation',
        'Data Tools& Tech Platforms': 'Data Tools & Tech Platforms',
        'Financial Markets, Forex & Trading': 'Finance & Trading',
        'Social Science Queries': 'Social Science Queries',
        'English Grammar Correction & Language Rules': 'English Grammar & Language'},
    'Pakistan': {
        'Urdu And English Translation': 'Urdu-English Translation',
        'General Health & Wellness Advice': 'Health & Wellness',
        'Math & Quantitative Calculations': 'Mathematics',
        'Online Earning Opportunities': 'Online Earning',
        'English Language Help': 'English Language Help',   
        'Programming': 'Programming',
        'Personal Finance, Utilities & Daily Tasks': 'Finance & Daily Tasks',
        'Image Generation': 'AI Image Generation',
        'Social Media Captions & Creative Writing.': 'Social Media & Creative Writing',
        'General Tech Help & Device Usage': 'Tech Help',
        'Religious Queries': 'Religious Queries',
        'Job Related': 'Job Related Queries',
        'Writing Help': 'Writing Help',
        'Biology & Life Sciences Academic Help': 'Biology & Science Help',
        'Current Affairs & Social Issues.': 'Current Affairs'}
}

In [7]:
df1['Final_Topic_renamed'] = df1['Final_Topic'].replace(topic_rename_mapping[country])

/tmp/ipykernel_4118943/1506131682.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Final_Topic_renamed'] = df1['Final_Topic'].replace(topic_rename_mapping[country])

In [8]:
df_theme = pd.read_csv(os.path.join("/home/kg766/shreyasi_analysis/chatgpt_data/final_analyses/topic_theme_mapping.csv"))
df1['theme'] = df1['Final_Topic_renamed'].map(df_theme[df_theme['country'] == country].set_index('Final_Topic_renamed')['theme'])

/tmp/ipykernel_4118943/3875480029.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['theme'] = df1['Final_Topic_renamed'].map(df_theme[df_theme['country'] == country].set_index('Final_Topic_renamed')['theme'])

In [9]:

# rename Final_Topic_renamed to Final_Topic and theme
df1 = df1.rename(columns={
    'convo_id' : 'conversation_id',
    'user_timestamp': 'conversation_timestamp',
    'topic_label_fine': 'Topic_Label_Fine',
    'topic_label_coarse': 'Topic_Label_Coarse',
    'Final_Topic_renamed': 'Clustering_Topic', 
    'theme': 'Clustering_Topic_Theme',
    'label_asking': 'asking_doing_expressing',
    'convo_id' : 'conversation_id',
    'label_work': 'work_coursework_personal',
    'multitasking': 'Multitasking',
    'human_alone': 'Complete_task_alone',
    'user_education': 'User_Education', 
    'AI_education': 'AI_Education'})

df1 = df1.drop(columns=['Final_Topic'])

In [10]:
# make rows with values appearing less than 5 times in the Final_Topic column as empty
topic_counts = df1['asking_doing_expressing'].value_counts()
df1.loc[~df1['asking_doing_expressing'].isin(topic_counts[topic_counts >= 5].index), 'asking_doing_expressing'] = None
df1.loc[~df1['work_coursework_personal'].isin(['Work', 'Coursework', 'Personal']), 'work_coursework_personal'] = None

In [11]:
for col in ['Topic_Label_Fine', 'Topic_Label_Coarse', 'asking_doing_expressing','work_coursework_personal', 'Multitasking', 'Complete_task_alone', 'User_Education', 'AI_Education']:
    print(f"Value counts for {col}:")
    print(df1[col].value_counts(dropna=False))
    print("\n")

Value counts for Topic_Label_Fine:
Topic_Label_Fine
specific_info                            4767
how_to_advice                            3272
personal_writing_or_communication        2841
tutoring_or_teaching                     2837
unclear                                  2572
computer_programming                     1993
translation                              1869
edit_or_critique_provided_text           1769
health_fitness_beauty_or_self_care       1105
creative_ideation                        1071
create_an_image                           906
mathematical_calculation                  853
argument_or_summary_generation            642
purchasable_products                      549
generate_or_retrieve_other_media          472
greetings_and_chitchat                    455
other                                     371
write_fiction                             364
relationships_and_personal_reflection     281
analyze_an_image                          117
asking_about_the_model                    108
cooking_and_recipes                       101
games_and_role_play                        80
data_analysis                              56
Name: count, dtype: int64


Value counts for Topic_Label_Coarse:
Topic_Label_Coarse
Practical Guidance     8285
Writing                7485
Seeking Information    5417
Other/Unknown          3051
Technical Help         2902
Multimedia             1495
Self-Expression         816
Name: count, dtype: int64


Value counts for asking_doing_expressing:
asking_doing_expressing
Asking        13072
Doing         10390
Expressing     5154
None            835
Name: count, dtype: int64


Value counts for work_coursework_personal:
work_coursework_personal
Personal      15611
Coursework     6894
Work           6125
None            821
Name: count, dtype: int64


Value counts for Multitasking:
Multitasking
No     18779
NaN     6404
Yes     4268
Name: count, dtype: int64


Value counts for Complete_task_alone:
Complete_task_alone
Yes    19666
NaN     6403
No      3382
Name: count, dtype: int64


Value counts for User_Education:
User_Education
8.0     8471
6.0     7686
12.0    4768
10.0    2841
0.0     1794
16.0     905
14.0     670
4.0      586
2.0      465
5.0      346
3.0      270
1.0      207
9.0      128
13.0      94
NaN       69
7.0       58
18.0      48
15.0      28
11.0      13
20.0       2
17.0       2
Name: count, dtype: int64


Value counts for AI_Education:
AI_Education
12.0    8648
0.0     4682
8.0     4187
10.0    4091
14.0    2242
6.0     2145
16.0    1844
13.0     258
4.0      242
9.0      236
15.0     168
5.0      147
2.0      129
3.0      101
18.0      97
7.0       73
NaN       69
1.0       51
11.0      25
20.0      10
17.0       6
Name: count, dtype: int64

In [12]:
print(df1.isna().sum())

user_id                         0
conversation_id                 0
conversation_timestamp          0
Topic_Label_Fine                0
Topic_Label_Coarse              0
asking_doing_expressing       835
work_coursework_personal      821
Multitasking                 6404
Complete_task_alone          6403
User_Education                 69
AI_Education                   69
Clustering_Topic             9276
Clustering_Topic_Theme      10504
dtype: int64

In [13]:
df1.columns

Index(['user_id', 'conversation_id', 'conversation_timestamp',
       'Topic_Label_Fine', 'Topic_Label_Coarse', 'asking_doing_expressing',
       'work_coursework_personal', 'Multitasking', 'Complete_task_alone',
       'User_Education', 'AI_Education', 'Clustering_Topic',
       'Clustering_Topic_Theme'],
      dtype='object')

In [14]:
len(df1), df1['user_id'].nunique(), df1['conversation_id'].nunique()

(29451, 206, 29451)

In [15]:
df1.to_csv(f"/home/kg766/shreyasi_analysis/data_for_paper/user_conversations_classified_{country}.csv", index=False)

In [16]:
# get unique user ids and gender

df_users = df1[['user_id', 'Age', 'Gender', 'Country']]
df_users = df_users.drop_duplicates(subset=['user_id', 'Age', 'Gender', 'Country'])
len(df_users), df_users['user_id'].nunique()

(246, 246)

In [17]:
df_users.to_csv(f"/home/kg766/shreyasi_analysis/data_for_paper_new/user_demographics_{country}.csv", index=False)

In [23]:
name = '/home/kg766/shreyasi_analysis/data_for_paper/user_demographics_India.csv'
df = pd.read_csv(name) 
# drop demographic details of users 
df.head()

    user_id  Age  Gender Country
0  13391811   32    Male   India
1   3141629   31    Male   India
2   6485773   31    Male   India
3  21554807   22    Male   India
4  15746085   32  Female   India

In [24]:
df.columns

Index(['user_id', 'Age', 'Gender', 'Country'], dtype='object')